/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/ui/button/Button.vue')['default']
    Collapsible: typeof import('./../components/ui/collapsible/Collapsible.vue')['default']
    CollapsibleContent: typeof import('./../components/ui/collapsible/CollapsibleContent.vue')['default']
    CollapsibleTrigger: typeof import('./../components/ui/collapsible/CollapsibleTrigger.vue')['default']
    Drawer: typeof import('./../components/ui/drawer/Drawer.vue')['default']
    DrawerContent: typeof import('./../components/ui/drawer/DrawerContent.vue')['default']
    DrawerDescription: typeof import('./../components/ui/drawer/DrawerDescription.vue')['default']
    DrawerFooter: typeof import('./../components/ui/drawer/DrawerFooter.vue')['default']
    DrawerHeader: typeof import('./../components/ui/drawer/DrawerHeader.vue')['default']
    DrawerOverlay: typeof import('./../components/ui/drawer/DrawerOverlay.vue')['default']
    DrawerTitle: typeof import('./../components/ui/drawer/DrawerTitle.vue')['default']
    Label: typeof import('./../components/ui/label/Label.vue')['default']
    Navbar: typeof import('./../components/Navbar.vue')['default']
    RadioGroup: typeof import('./../components/ui/radio-group/RadioGroup.vue')['default']
    RadioGroupItem: typeof import('./../components/ui/radio-group/RadioGroupItem.vue')['default']
    ResizableHandle: typeof import('./../components/ui/resizable/ResizableHandle.vue')['default']
    ResizablePanelGroup: typeof import('./../components/ui/resizable/ResizablePanelGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./../components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./../components/ui/scroll-area/ScrollBar.vue')['default']
    Separator: typeof import('./../components/ui/separator/Separator.vue')['default']
    Sheet: typeof import('./../components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./../components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./../components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./../components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./../components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./../components/ui/sheet/SheetHeader.vue')['default']
    SheetTitle: typeof import('./../components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./../components/ui/sheet/SheetTrigger.vue')['default']
    Slider: typeof import('./../components/ui/slider/Slider.vue')['default']
    Switch: typeof import('./../components/ui/switch/Switch.vue')['default']
    Tabs: typeof import('./../components/ui/tabs/Tabs.vue')['default']
    TabsContent: typeof import('./../components/ui/tabs/TabsContent.vue')['default']
    TabsList: typeof import('./../components/ui/tabs/TabsList.vue')['default']
    TabsTrigger: typeof import('./../components/ui/tabs/TabsTrigger.vue')['default']
    Toast: typeof import('./../components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./../components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./../components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./../components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./../components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./../components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./../components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./../components/ui/toast/ToastViewport.vue')['default']
    Tooltip: typeof import('./../components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./../components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./../components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./../components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
