/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../components/ui/button/Button.vue')['default']
    Dialog: typeof import('./../components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./../components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./../components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./../components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./../components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./../components/ui/dialog/DialogHeader.vue')['default']
    DialogScrollContent: typeof import('./../components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./../components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./../components/ui/dialog/DialogTrigger.vue')['default']
    Input: typeof import('./../components/ui/input/Input.vue')['default']
    Label: typeof import('./../components/ui/label/Label.vue')['default']
    Navbar: typeof import('./../components/Navbar.vue')['default']
    ResizableHandle: typeof import('./../components/ui/resizable/ResizableHandle.vue')['default']
    ResizablePanelGroup: typeof import('./../components/ui/resizable/ResizablePanelGroup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollArea: typeof import('./../components/ui/scroll-area/ScrollArea.vue')['default']
    ScrollBar: typeof import('./../components/ui/scroll-area/ScrollBar.vue')['default']
    Separator: typeof import('./../components/ui/separator/Separator.vue')['default']
    Slider: typeof import('./../components/ui/slider/Slider.vue')['default']
    Toast: typeof import('./../components/ui/toast/Toast.vue')['default']
    ToastAction: typeof import('./../components/ui/toast/ToastAction.vue')['default']
    ToastClose: typeof import('./../components/ui/toast/ToastClose.vue')['default']
    ToastDescription: typeof import('./../components/ui/toast/ToastDescription.vue')['default']
    Toaster: typeof import('./../components/ui/toast/Toaster.vue')['default']
    ToastProvider: typeof import('./../components/ui/toast/ToastProvider.vue')['default']
    ToastTitle: typeof import('./../components/ui/toast/ToastTitle.vue')['default']
    ToastViewport: typeof import('./../components/ui/toast/ToastViewport.vue')['default']
    Tooltip: typeof import('./../components/ui/tooltip/Tooltip.vue')['default']
    TooltipContent: typeof import('./../components/ui/tooltip/TooltipContent.vue')['default']
    TooltipProvider: typeof import('./../components/ui/tooltip/TooltipProvider.vue')['default']
    TooltipTrigger: typeof import('./../components/ui/tooltip/TooltipTrigger.vue')['default']
  }
}
